version: '3'
services:
  event-nginx:
    container_name: event-nginx
    image: nginx:1.13
    restart: always
    ports:
      - 80:80
      - 81:81
      - 443:443
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - app
      - app-streaming

  app:
    container_name: app
    image: app
    build: ./app
    environment:
      - SERVER_PORT=8080
    ports:
      - "8080:8080"


  app-streaming:
    container_name: app-streaming
    image: app-streaming
    build: ./app_streaming
    environment:
      - SERVER_PORT=8181
    ports:
      - "8181:8181"

