version: '3'
services:
  event-nginx:
    container_name: event-nginx
    image: nginx:1.13
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/error.log:/etc/nginx/error_log.log
    depends_on:
      - app-streaming
      - app

  app-streaming:
    container_name: app-streaming
    image: app-streaming
    build: ./app_streaming
    environment:
      - SERVER_PORT=8080
    ports:
      - "8080:8080"
    expose:
      - "80"

  app:
    container_name: app
    image: app
    build: ./app
    environment:
      - SERVER_PORT=5000
    ports:
      - "5000:5000"
    expose:
      - "80"
