version: '3'
services:
  event-nginx:
    container_name: event-nginx
    image: nginx:1.13
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - acquirer-app

  acquirer-app:
    container_name: acquirer-app
    image: acquirer-app
    build: ./app
    environment:
      - SERVER_PORT=8080
    ports:
      - "8080:8080"