version: '3'
services:
  app-streaming:
    container_name: app-streaming
    image: app-streaming
    build: ./app_streaming
    environment:
      - SERVER_PORT=8080
    ports:
      - "8080:8080"
      - "9200:9200"
      - "9300:9300"
    expose:
      - "80"

  app:
    container_name: app
    image: app
    build: ./app
    environment:
      - SERVER_PORT=5000
    ports:
      - "5000:5000"
    expose:
      - "80"
